# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --display_data=true
    # <- Optional: specify video codec (auto, h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm" \
  --dataset.streaming_encoding=true \
  # --dataset.vcodec=auto \
  --dataset.encoder_threads=2
```
"""

import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.feature_utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    openarm_mini,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.device_utils import get_safe_torch_device
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


from lerobot.robots import bi_koch_follower
from lerobot.teleoperators import bi_koch_leader


# 这两个 dataclass 是 `lerobot-record` 的配置入口：
# 1. `DatasetRecordConfig` 只负责“数据怎么存”
# 2. `RecordConfig` 负责“整个录制流程怎么跑”
# 这样拆开后，dataset 相关参数可以独立理解，不会和 robot / teleop / policy
# 的运行时参数混在一起。
@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path'). If None, defaults to $HF_LEROBOT_HOME/repo_id.
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1', 'auto',
    # or hardware-specific: 'h264_videotoolbox', 'h264_nvenc', 'h264_vaapi', 'h264_qsv'.
    # Use 'auto' to auto-detect the best available hardware encoder.
    vcodec: str = "libsvtav1"
    # Enable streaming video encoding: encode frames in real-time during capture instead
    # of writing PNG images first. Makes save_episode() near-instant. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when using streaming encoding.
    # ~1s buffer at 30fps. Provides backpressure if the encoder can't keep up.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None = auto (codec default).
    # Lower values reduce CPU usage, maps to 'lp' (via svtav1-params) for libsvtav1 and 'threads' for h264/hevc..
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        """校验 dataset 级别的必要字段。

        作用：
        - 在真正连接机器人、创建数据集之前，尽早拦住无效配置。
        - 这里目前只强制 `single_task` 必填，因为后续每一帧都会把 task 文本
          写入 dataset，policy 条件输入也会依赖它。
        """
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    # `robot` 和 `dataset` 是录制一定需要的两部分。
    # `teleop` 和 `policy` 不要求同时存在，但至少要有一个控制源，否则 robot
    # 只能读 observation，无法产生 action。
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        """补全 policy 配置，并校验控制源是否合法。

        作用：
        - 从 CLI 中重新解析 `--policy.path`，把它变成 `PreTrainedConfig`。
        - 这是 train / eval / record 共用的一种模式：dataclass 里存的是结构化配置，
          但预训练权重路径更适合在这里统一补齐。
        - 同时保证控制源不是空的：至少要么 teleop，要么 policy。
        """
        # 这里再次从 CLI 取 path，是因为 `policy.path` 这种“路径型字段”在真正
        # 加载预训练配置时，还需要合并用户通过 CLI 传入的 policy override。
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            # 例如用户除了 `--policy.path=...`，还可能额外传
            # `--policy.device=cuda` 这种 override；这里一起吃进去。
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        # 整个 `record_loop` 依赖 action 来源。没有 teleop 也没有 policy 时，
        # 录制流程虽然能采 observation，但无法控制机器人，因此直接报错。
        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """告诉 parser：`policy` 下面有 path-like 字段需要特殊处理。

        作用：
        - 允许命令行使用 `--policy.path=local/dir`。
        - 这会让 parser 知道后续需要从该目录读取模型配置。
        """
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
):
    """执行一段连续的控制循环。

    这是 `record` 子系统里最核心的函数。可以把它理解成：
    “以固定 fps 重复执行 observation -> action -> robot -> dataset 的闭环”。

    这个函数会被上层 `record()` 复用两次：
    1. 正式录制 episode 时：
       - `dataset` 不为 None
       - 每个 tick 都会写一帧到数据集缓冲区
    2. episode 之间 reset 时：
       - `dataset` 仍然传入，但上层也可能用“无录制控制窗口”的方式复用同样逻辑
       - 目的是给人时间把场景和机器人恢复到下一条轨迹的起点

    参数作用概览：
    - `robot`：真实硬件接口，负责读 observation 和发 action
    - `teleop_action_processor`：把 teleop 原始动作变成统一动作表示
    - `robot_action_processor`：把统一动作表示变成机器人真正接受的动作
    - `robot_observation_processor`：把原始 observation 变成统一特征格式
    - `policy/preprocessor/postprocessor`：policy 控制路径的三件套
    - `events`：键盘事件状态，允许中断 / 重录 / 停止
    """
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        # 多 teleop 目前是 LeKiwi 的专用分支：
        # 一个机械臂 teleop 负责 arm，键盘 teleop 负责 base。
        # 所以这里要先把两种控制器从 list 中拆出来。
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # 每个 episode / reset 窗口开始前都把 policy 和 processor 状态清空。
    # 这样可以避免上一个 episode 的历史缓存影响当前 episode。
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    no_action_count = 0
    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        # `events` 来自键盘监听线程：
        # - 右键：提前结束当前窗口
        # - 左键：提前结束并标记重录
        # - ESC：停止整个录制流程
        # 这里的职责只是“感知并退出本轮循环”，真正怎么处理这些事件由上层 `record()`
        # 决定。
        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Step 1. 从真实机器人读取当前 observation。
        # 这是整个闭环的起点：policy 和 dataset 都依赖这份观测。
        obs = robot.get_observation()

        # Step 2. 对 observation 做统一处理。
        # 这个 processor 会把“硬件原始输出”整理成 LeRobot 统一约定的 observation
        # 格式，例如 state / image 的键名、shape、类型等。
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            # `build_dataset_frame` 的作用是把处理后的 observation 映射成 dataset
            # 的平铺特征字典。
            # 这里非常关键：policy 控制路径复用了 dataset 的特征表示，这样
            # “模型实际看到的输入”和“磁盘里存下来的 observation”天然对齐。
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Step 3. 选择 action 来源。
        # 这个函数支持三种控制模式：
        # 1. policy 控制
        # 2. 单一 teleop 控制
        # 3. LeKiwi 的多 teleop 控制
        if policy is not None and preprocessor is not None and postprocessor is not None:
            # policy 分支走的是“同步推理”：
            # observation_frame
            #   -> preprocessor
            #   -> policy.select_action()
            #   -> postprocessor
            #   -> action tensor
            #
            # `predict_action` 封装了这整条链，所以 record_loop 本身不直接关心
            # 张量搬运、amp、图像 CHW 转换等细节。
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            # policy 输出通常是 tensor / ndarray 风格的向量。
            # `make_robot_action` 会用 dataset schema 中的 action feature 名称，
            # 把它还原成“关节名 -> 数值”的 RobotAction 字典。
            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            # 单一 teleop 分支：直接从 teleoperator 读取动作。
            # 对 unitree_g1 这种机器人，teleop 之前还会接收反馈。
            if robot.name == "unitree_g1":
                teleop.send_feedback(obs)
            act = teleop.get_action()

            # teleop 原始动作也要经过 processor，目的是和 policy 分支统一到
            # 同一套动作表示，后面 robot_action_processor 才能共用。
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            # LeKiwi 多 teleop 分支：
            # - arm_action 来自机械臂 teleop
            # - keyboard_action 来自键盘
            # - 最后把它们合并成一个完整的机器人动作
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            no_action_count += 1
            if no_action_count == 1 or no_action_count % 10 == 0:
                logging.warning(
                    "No policy or teleoperator provided, skipping action generation. "
                    "This is likely to happen when resetting the environment without a teleop device. "
                    "The robot won't be at its rest position at the start of the next episode."
                )
            continue

        # Step 4. 无论 action 来自 policy 还是 teleop，都会在这里汇合。
        # `robot_action_processor` 的职责是把统一动作表示转换成“真正发给机器人”
        # 的动作格式，例如做键名重排、裁剪、硬件接口适配等。
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        _sent_action = robot.send_action(robot_action_to_send)

        # Step 5. 把这一帧写进 dataset buffer。
        # 注意这里写入的是“本轮控制选择出来的 action_values”，然后和当前 observation
        # 一起组成一帧，真正落盘发生在上层 `dataset.save_episode()`。
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        # 可选的可视化分支：把当前观测和动作发送到 Rerun。
        if display_data:
            log_rerun_data(
                observation=obs_processed, action=action_values, compress_images=display_compressed_images
            )

        # Step 6. 维持近似恒定的控制频率。
        # 每个 tick 的计算耗时不同，所以这里用“目标周期 - 当前耗时”的方式补 sleep。
        dt_s = time.perf_counter() - start_loop_t

        sleep_time_s: float = 1 / fps - dt_s
        if sleep_time_s < 0:
            logging.warning(
                f"Record loop is running slower ({1 / dt_s:.1f} Hz) than the target FPS ({fps} Hz). Dataset frames might be dropped and robot control might be unstable. Common causes are: 1) Camera FPS not keeping up 2) Policy inference taking too long 3) CPU starvation"
            )

        precise_sleep(max(sleep_time_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    """`lerobot-record` 的顶层入口。

    作用：
    1. 初始化日志和可视化
    2. 构造 robot / teleop / processors
    3. 创建或恢复 dataset
    4. 按需加载 policy 与 pre/post processors
    5. 连接硬件、启动键盘监听
    6. 按 episode 反复调用 `record_loop`
    7. 统一执行保存、上传、断连、清理

    可以把这个函数理解成“episode 级调度器”，而不是单步控制器。
    真正每个 tick 做什么，是 `record_loop()` 的职责；
    `record()` 更像是在组织：
    - 什么时候开始一条 episode
    - 什么时候进入 reset
    - 什么时候保存或丢弃当前 episode
    """
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    # 先根据配置构造硬件对象，但此时还没有真正 connect。
    # 这样如果后面 dataset / policy 初始化失败，不会留下半连接状态的设备。
    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    # 三类默认 processor 分别负责：
    # - teleop_action_processor：teleop 原始动作 -> 统一动作表示
    # - robot_action_processor：统一动作表示 -> 真正发送给 robot 的动作
    # - robot_observation_processor：robot 原始 observation -> 统一 observation 表示
    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    # dataset schema 不是手写的，而是从 processors + robot feature 定义里推导出来的。
    # 这样可以保证：
    # - 你记录下来的字段
    # - policy 实际吃到的字段
    # - processor 实际生成的字段
    # 三者保持一致。
    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            # resume 分支：复用已有 dataset 的 metadata，并重新挂上图像写线程 / 视频编码器。
            # 这是“继续往旧数据集后面追加 episode”，不是重新创建数据集。
            num_cameras = len(robot.cameras) if hasattr(robot, "cameras") else 0
            dataset = LeRobotDataset.resume(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
                image_writer_processes=cfg.dataset.num_image_writer_processes if num_cameras > 0 else 0,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * num_cameras
                if num_cameras > 0
                else 0,
            )
            # 恢复老数据集时，必须确认“当前 robot + 当前 processors 推导出的 schema”
            # 和历史 dataset 真的是兼容的，否则继续写会把数据集弄坏。
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # create 分支：新建一个空数据集，然后后面逐 episode 往里追加。
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

        # policy 是可选的：如果用户是纯 teleop 录数据，这里会保持 None。
        # 如果有 policy，则从 checkpoint / hub 加载成可直接 rollout 的对象。
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            # 这里加载 policy 配套的处理链：
            # - preprocessor：把 observation 变成模型输入
            # - postprocessor：把模型输出变成统一动作表示
            #
            # `rename_map` 的作用是把“当前 robot / dataset 的观测键名”映射成
            # “policy 训练时期待的键名”。
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        # 到这里，配置、dataset、policy 都准备好了，才真正连接硬件。
        robot.connect()
        if teleop is not None:
            teleop.connect()

        # 键盘监听返回一个共享字典 `events`，record_loop 和 record() 都会读它。
        listener, events = init_keyboard_listener()

        if not cfg.dataset.streaming_encoding:
            logging.info(
                "Streaming encoding is disabled. If you have capable hardware, consider enabling it for way faster episode saving. --dataset.streaming_encoding=true --dataset.encoder_threads=2 # --dataset.vcodec=auto. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding"
            )

        # VideoEncodingManager 统一托管视频编码相关资源。
        # 这样即使中途异常退出，也能尽量走到一致的收尾流程。
        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                # 进入一条新的 episode：
                # - 播报提示
                # - 调用 record_loop 执行固定时长的控制与录制
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                )

                # 一条 episode 结束后，通常要给操作者一点时间恢复场景。
                # 所以这里会再跑一个“reset 窗口”：
                # - 依然调用同一个 record_loop
                # - 但语义上这是 reset，不是正式采样
                #
                # 最后一条 episode 后通常不需要 reset，除非用户按了重录键。
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )

                # 左键会把刚才录的 episode 标记为无效。
                # 这里清掉当前 episode buffer，不写盘，然后直接回到 while 顶部重录。
                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                # 只有没有被标记为重录时，才真正把当前 episode 提交到磁盘。
                dataset.save_episode()
                recorded_episodes += 1
    finally:
        # finally 的作用是兜底清理：
        # 无论是正常结束、键盘中断还是异常报错，都会尽量走这条路径。
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            # finalize 会把 dataset 的写入状态收尾，例如刷掉缓冲、关闭资源等。
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        # headless 环境本来就不会启动 pynput listener，所以这里只在非 headless
        # 场景下尝试 stop。
        if not is_headless() and listener:
            listener.stop()

        # 上传是最后一步，只有本地资源都安全关闭后才做。
        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    """CLI 主入口。

    作用很简单：
    - 先注册第三方插件，确保扩展出来的 robot / policy / env 类型可见
    - 再进入 `record()`
    """
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
